### PR TITLE
Make start_grabbing function non-mut again for better useability

### PR DESCRIPTION
**Pull request by hirschenberger**

### CODE REVIEW

**Comment by astraw** [comment]
Thanks, I'm not using the `stream` feature so I will trust this works nicely for you.

This will require a version bump. Any other changes you have coming before 0.4?

**Comment by hirschenberger** [comment]
No, I just had problems storing an InstantCamera in my state struct, which must be pinned to use streamimg but had to be mut to call the start_grabbing function. So I changed it to use interior mutability by using a RefCell for the fd.

I have no further changes yet.

**Comment by astraw** [comment]
Thanks again. I released this as 0.3.3.

(It is probably debatable if introducing a compiler warning - as will happen here - is a breaking change. But I decided not to bump this as a breaking change. In the worst case scenario, I could yank 0.3.3 and re-publish as 0.4.0.)

**Comment by hirschenberger** [comment]
I would consider it a BC as the function signature is changed, but it's pre 1.0 and so everything is allowed and as it only really breaks builds for users that have enabled warnings-as-erros, I'd be fine with it.

BTW: Have you read the email I wrote to you of was it a victim of your spam folder?

**Comment by astraw** [comment]
The warnings-as-errors issue is exactly why this is debatable, but given that much code written for rust 1.0 would trigger compiler warnings today, I'll call it acceptable unless someone strongly complains.

No, I didn't get any email from you but would be happy to.

**Comment by hirschenberger** [comment]
I can also paste  it here, nothing secret:

```
Hey Andrew,

I'm Falco (the guy that added the stream functionality to pylon-cxx). I saw that you're also working in the imageprocessing field.
Maybe you're interested in some crate that I've written. We use something like that (written in Elixir) in our department for image storage and cleanup on our industrial inspection systems.

I've rewritten it in rust (RIIR) and made it OSS just for fun, learning and to jump on the RIIR bandwagon. I'd be glad if someone would actually use it.

https://gitlab.com/hirschenberger/archivist

Regards, Falco
```

**Pull request merged**
