### PR TITLE
Fix occasional hangups in async stream implementation

### PR DESCRIPTION
**Pull request by hirschenberger**
The implemenation was faulty which led to occasional hangups.

### CODE REVIEW

**Comment by astraw** [comment]
Thanks, I will try this. Where did you experience occasional hangups? Was it related to transport later (e.g. USB3 cameras, GigE)? Is there anyway to reproduce easily the underlying problem.

**Comment by hirschenberger** [comment]
I had the Problem with the CAMEMU, it may be unrelated to a camera model or protocol. The problem was that `clear_ready` was called every time the waitobject woke up, but the documentation clearly states:


> It is critical that this function not be called unless your code actually observes that the file descriptor is not ready. Do not call it simply because, for example, a read succeeded; it should be called when a read is observed to block.

So the clearing should only happen when `retrieve_result` returns `false` and the retrieval should be retried with `continue` and looping the whole block. 

Also returning `Poll::Pending` from the function is wrong, instead it must also retry.

**Comment by astraw** [comment]
Thanks for the clarifications.

In my testing on both macOS with pylon 7.3 and CAMEMU and on linux with pylon 6.2 with a real camera, the `async-grab` example hangs with this PR at dc4aa6c865b596ad8c5e2726332e1a723886f4b1 (but not without it in a428416724e14a8099aa2da8659af74def8c183f).

Can you check with that example?

(I can believe there are problems with the current implementation. I certainly have not tested the async implementation very much. My application, [Strand Camera](https://github.com/strawlab/strand-braid), currently uses the sync implementation.)

**Comment by hirschenberger** [comment]
You're right, there seems to be some racecondition. I can reproduce the hanging in the tests, although my app works.
I asked in the Tokio-Discord for help and got the current version as an answer but obviously it's not working. Async Rust is a beast if you try to implement own primitives.
I'll rework the PR.

**Comment by astraw** [comment]
Thanks. It is "good" that you can reproduce the hanging test. Perhaps the test itself is wrong?

**Comment by hirschenberger** [comment]
No, the test looks legit, if I decrease the framerate, the example works. I think I have a working version now. Can you please also check if it works for you?

**Comment by astraw** [comment]
Yes, the test works for me now. So far I tested only with macOS with pylon 7.3 and CAMEMU. I will put out a new release soon with this. Thanks.

**Pull request merged**
